In [9]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt


df = pd.read_csv(r'C:\Users\usrer\Desktop\books for study\4 КУРС\мл\glass.csv')


In [10]:
df.shape

(214, 10)

In [11]:
df['RI'] = (df['RI'].values - df['RI'].min())/(df['RI'].max()-df['RI'].min())
df['Na']= (df['Na'].values - df['Na'].min())/(df['Na'].max()-df['Na'].min())
df['Mg']= (df['Mg'].values - df['Mg'].min())/(df['Mg'].max()-df['Mg'].min())
df['Al']= (df['Al'].values - df['Al'].min())/(df['Al'].max()-df['Al'].min())
df['Si']= (df['Si'].values - df['Si'].min())/(df['Si'].max()-df['Si'].min())
df['K']=  (df['K'].values - df['K'].min())/(df['K'].max()-df['K'].min())
df['Ca']= (df['Ca'].values - df['Ca'].min())/(df['Ca'].max()-df['Ca'].min())
df['Ba']= (df['Ba'].values - df['Ba'].min())/(df['Ba'].max()-df['Ba'].min())
df['Fe']= (df['Fe'].values - df['Fe'].min())/(df['Fe'].max()-df['Fe'].min())

In [12]:
df.head()

RI        Na        Mg        Al        Si         K        Ca   Ba  \
0  0.432836  0.437594  1.000000  0.252336  0.351786  0.009662  0.308550  0.0   
1  0.283582  0.475188  0.801782  0.333333  0.521429  0.077295  0.223048  0.0   
2  0.220808  0.421053  0.790646  0.389408  0.567857  0.062802  0.218401  0.0   
3  0.285777  0.372932  0.821826  0.311526  0.500000  0.091787  0.259294  0.0   
4  0.275241  0.381955  0.806236  0.295950  0.583929  0.088567  0.245353  0.0   

    Fe  Type  
0  0.0     1  
1  0.0     1  
2  0.0     1  
3  0.0     1  
4  0.0     1

In [103]:
df.Type.unique()

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [80]:
X.shape

(70, 10)

In [81]:
def activation(x):
    return 1/(1+np.exp(-x))
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

In [82]:
X.iloc[0]

RI     0.432836
Na     0.437594
Mg     1.000000
Al     0.252336
Si     0.351786
K      0.009662
Ca     0.308550
Ba     0.000000
Fe     0.000000
One    1.000000
Name: 0, dtype: float64

In [140]:
b=[]
alpha =0.01
classes =7
for i in range (classes):
    df1=df[df['Type']==i]
    X = df1[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']]
    X['One']=1
    Y=df1['Type']
    n=len(X)
    if n==0:
        continue
    W1 = np.random.randn(10,10)
    W2 = np.random.randn(10,7)
    y= np.zeros((7))
    y[i]=1
    for j in range (n):
        d = X.iloc[j]
        for k in range(2000):
            h = activation(np.dot(d, W1))
            out = np.dot(h, W2)

            error = y-out  
            erdelta = np.dot(W2,error *(out*(1-out)) )    


            W1=W1 - alpha*np.dot(h, erdelta)
            W2 =W2 -  alpha*np.dot(out, error)
    b.append(W1)
    b.append(W2)
    c=0
    b.append(c)



In [141]:
b

[array([[-2.28742556, -1.73750653, -5.63333137, -2.07660642, -3.17273733,
         -2.98234529, -3.16728024, -2.6631276 , -2.85986014, -3.60017594],
        [-3.74745353, -4.08269482, -1.73597036, -4.10790048, -4.28585633,
         -3.02671672, -1.83068022, -3.20266978, -3.81389719, -1.16564795],
        [-2.64761723, -4.19284544, -3.86593987, -1.78540448, -3.29371513,
         -3.27976654, -3.73217726, -3.67003412, -2.72837282, -1.94636395],
        [-3.55972931, -3.64875667, -3.19189981, -2.03883264, -2.99415603,
         -3.70512889, -2.06526507, -3.23380409, -3.61397339, -3.51124652],
        [-2.85419103, -2.258849  , -3.53921561, -2.81458176, -2.2732277 ,
         -2.01422692, -3.83438889, -2.28923172, -3.80262808, -3.72704746],
        [-3.30587058, -2.39395902, -3.90279105, -4.89213123, -1.66198479,
         -3.63849681, -3.69724249, -1.46320984, -3.13004206, -3.14284298],
        [-2.5620347 , -4.98000539, -3.08835204, -3.49722499, -2.7935863 ,
         -1.85356081, -3.2727018

In [87]:
W1

array([[-1.13729901,  0.15447865,  0.41572277, -1.27468795,  0.16422844,
        -0.05661137, -1.47395195,  0.48278214, -0.81063441,  0.50728037],
       [ 1.39554252,  3.3097886 , -0.30942009,  0.84363614,  0.9469646 ,
         0.31530871,  0.8405068 ,  1.043135  , -0.29925866,  0.74290312],
       [ 0.106818  ,  0.89383804,  0.66757214, -0.00470343,  1.97700185,
         1.53846552,  1.04617478, -1.18616888, -1.5821926 , -1.26134347],
       [ 2.31513247,  0.45056214, -0.40504686,  1.09791669,  0.46670476,
        -0.16380445,  1.34441717,  0.1151666 ,  0.9891034 , -2.18133453],
       [ 0.75533355,  0.08708719, -0.34449255, -1.57074316,  1.10051218,
        -1.3714139 , -0.25614486, -1.40285248,  0.62733094, -0.80552078],
       [-1.0752811 , -0.18792263,  0.43696182,  1.27975824, -0.05667891,
         1.41058442, -0.81832297, -1.00247849, -1.26187646,  0.04591262],
       [-1.02217037, -0.26349708, -0.18828079, -1.18785193, -1.16411716,
        -0.52160022,  0.84098916, -0.89102414

In [65]:
error

array([ 0.86976636, -0.14852439, -0.10617492, -0.17278683, -0.10371601,
       -0.13342486, -0.20513934])

In [40]:
h = activation(np.dot(X.iloc[[1]], W1) + B1)

In [ ]:
loss = h- y 
    loss1 = np.dot(np.dot(W2.T, loss.T),np.dot(h, (1-h).T)) 
    for z in range (len(W1)):
        for j in range (len(W1[z])):
            W1[z][j]= W1[z][j]- X.iloc[[i],z]*loss[z]
    for k in range (len(W2)):
        W2[k] = W2[k] 

In [82]:
loss.shape

(1, 9)

In [70]:
h.shape

(1, 9)

In [71]:
out.shape

(1, 7)

In [81]:
X.iloc[[1]]

RI        Na        Mg        Al        Si         K        Ca   Ba  \
1  0.283582  0.475188  0.801782  0.333333  0.521429  0.077295  0.223048  0.0   

    Fe  
1  0.0

In [23]:
h.shape

(70, 9)

In [24]:
out.shape

(70, 7)

In [26]:
Y.shape

(70,)

In [61]:
Y.shape

(214,)